<?php

/**
 * List of countries and territories
 * 
 * Copyright (c) Rhymix Developers and Contributors
 */
return array(
	array(
		'iso_3166_1_alpha2' => 'AF',
		'iso_3166_1_alpha3' => 'AFG',
		'iso_3166_1_numeric' => '004',
		'calling_code' => '93',
		'cctld' => 'af',
		'name_english' => 'Afghanistan',
		'name_korean' => '아프가니스탄',
		'name_native' => 'افغانستان',
	),
	array(
		'iso_3166_1_alpha2' => 'AL',
		'iso_3166_1_alpha3' => 'ALB',
		'iso_3166_1_numeric' => '008',
		'calling_code' => '355',
		'cctld' => 'al',
		'name_english' => 'Albania',
		'name_korean' => '알바니아',
		'name_native' => 'Shqipëria',
	),
	array(
		'iso_3166_1_alpha2' => 'AQ',
		'iso_3166_1_alpha3' => 'ATA',
		'iso_3166_1_numeric' => '010',
		'calling_code' => '672',
		'cctld' => 'aq',
		'name_english' => 'Antarctica',
		'name_korean' => '남극',
		'name_native' => 'Antarctica',
	),
	array(
		'iso_3166_1_alpha2' => 'DZ',
		'iso_3166_1_alpha3' => 'DZA',
		'iso_3166_1_numeric' => '012',
		'calling_code' => '213',
		'cctld' => 'dz',
		'name_english' => 'Algeria',
		'name_korean' => '알제리',
		'name_native' => 'الجزائر',
	),
	array(
		'iso_3166_1_alpha2' => 'AS',
		'iso_3166_1_alpha3' => 'ASM',
		'iso_3166_1_numeric' => '016',
		'calling_code' => '1-684',
		'cctld' => 'as',
		'name_english' => 'American Samoa',
		'name_korean' => '아메리칸 사모아',
		'name_native' => 'Amerika Sāmoa',
	),
	array(
		'iso_3166_1_alpha2' => 'AD',
		'iso_3166_1_alpha3' => 'AND',
		'iso_3166_1_numeric' => '020',
		'calling_code' => '376',
		'cctld' => 'ad',
		'name_english' => 'Andorra',
		'name_korean' => '안도라',
		'name_native' => 'Andorra',
	),
	array(
		'iso_3166_1_alpha2' => 'AO',
		'iso_3166_1_alpha3' => 'AGO',
		'iso_3166_1_numeric' => '024',
		'calling_code' => '244',
		'cctld' => 'ao',
		'name_english' => 'Angola',
		'name_korean' => '앙골라',
		'name_native' => 'Angola',
	),
	array(
		'iso_3166_1_alpha2' => 'AG',
		'iso_3166_1_alpha3' => 'ATG',
		'iso_3166_1_numeric' => '028',
		'calling_code' => '1-268',
		'cctld' => 'ag',
		'name_english' => 'Antigua and Barbuda',
		'name_korean' => '앤티가 바부다',
		'name_native' => 'Antigua and Barbuda',
	),
	array(
		'iso_3166_1_alpha2' => 'AZ',
		'iso_3166_1_alpha3' => 'AZE',
		'iso_3166_1_numeric' => '031',
		'calling_code' => '994',
		'cctld' => 'az',
		'name_english' => 'Azerbaijan',
		'name_korean' => '아제르바이잔',
		'name_native' => 'Azərbaycan',
	),
	array(
		'iso_3166_1_alpha2' => 'AR',
		'iso_3166_1_alpha3' => 'ARG',
		'iso_3166_1_numeric' => '032',
		'calling_code' => '54',
		'cctld' => 'ar',
		'name_english' => 'Argentina',
		'name_korean' => '아르헨티나',
		'name_native' => 'Argentina',
	),
	array(
		'iso_3166_1_alpha2' => 'AU',
		'iso_3166_1_alpha3' => 'AUS',
		'iso_3166_1_numeric' => '036',
		'calling_code' => '61',
		'cctld' => 'au',
		'name_english' => 'Australia',
		'name_korean' => '호주',
		'name_native' => 'Australia',
	),
	array(
		'iso_3166_1_alpha2' => 'AT',
		'iso_3166_1_alpha3' => 'AUT',
		'iso_3166_1_numeric' => '040',
		'calling_code' => '43',
		'cctld' => 'at',
		'name_english' => 'Austria',
		'name_korean' => '오스트리아',
		'name_native' => 'Österreich',
	),
	array(
		'iso_3166_1_alpha2' => 'BS',
		'iso_3166_1_alpha3' => 'BHS',
		'iso_3166_1_numeric' => '044',
		'calling_code' => '1-242',
		'cctld' => 'bs',
		'name_english' => 'Bahamas',
		'name_korean' => '바하마',
		'name_native' => 'Bahamas',
	),
	array(
		'iso_3166_1_alpha2' => 'BH',
		'iso_3166_1_alpha3' => 'BHR',
		'iso_3166_1_numeric' => '048',
		'calling_code' => '973',
		'cctld' => 'bh',
		'name_english' => 'Bahrain',
		'name_korean' => '바레인',
		'name_native' => 'البحرين',
	),
	array(
		'iso_3166_1_alpha2' => 'BD',
		'iso_3166_1_alpha3' => 'BGD',
		'iso_3166_1_numeric' => '050',
		'calling_code' => '880',
		'cctld' => 'bd',
		'name_english' => 'Bangladesh',
		'name_korean' => '방글라데시',
		'name_native' => 'বাংলাদেশ',
	),
	array(
		'iso_3166_1_alpha2' => 'AM',
		'iso_3166_1_alpha3' => 'ARM',
		'iso_3166_1_numeric' => '051',
		'calling_code' => '374',
		'cctld' => 'am',
		'name_english' => 'Armenia',
		'name_korean' => '아르메니아',
		'name_native' => 'Հայաստան',
	),
	array(
		'iso_3166_1_alpha2' => 'BB',
		'iso_3166_1_alpha3' => 'BRB',
		'iso_3166_1_numeric' => '052',
		'calling_code' => '1-246',
		'cctld' => 'bb',
		'name_english' => 'Barbados',
		'name_korean' => '바베이도스',
		'name_native' => 'Barbados',
	),
	array(
		'iso_3166_1_alpha2' => 'BE',
		'iso_3166_1_alpha3' => 'BEL',
		'iso_3166_1_numeric' => '056',
		'calling_code' => '32',
		'cctld' => 'be',
		'name_english' => 'Belgium',
		'name_korean' => '벨기에',
		'name_native' => 'België',
	),
	array(
		'iso_3166_1_alpha2' => 'BM',
		'iso_3166_1_alpha3' => 'BMU',
		'iso_3166_1_numeric' => '060',
		'calling_code' => '1-441',
		'cctld' => 'bm',
		'name_english' => 'Bermuda',
		'name_korean' => '버뮤다',
		'name_native' => 'Bermuda',
	),
	array(
		'iso_3166_1_alpha2' => 'BT',
		'iso_3166_1_alpha3' => 'BTN',
		'iso_3166_1_numeric' => '064',
		'calling_code' => '975',
		'cctld' => 'bt',
		'name_english' => 'Bhutan',
		'name_korean' => '부탄',
		'name_native' => 'འབྲུག་ཡུལ',
	),
	array(
		'iso_3166_1_alpha2' => 'BO',
		'iso_3166_1_alpha3' => 'BOL',
		'iso_3166_1_numeric' => '068',
		'calling_code' => '591',
		'cctld' => 'bo',
		'name_english' => 'Bolivia',
		'name_korean' => '볼리비아',
		'name_native' => 'Bolivia',
	),
	array(
		'iso_3166_1_alpha2' => 'BA',
		'iso_3166_1_alpha3' => 'BIH',
		'iso_3166_1_numeric' => '070',
		'calling_code' => '387',
		'cctld' => 'ba',
		'name_english' => 'Bosnia and Herzegovina',
		'name_korean' => '보스니아 헤르체고비나',
		'name_native' => 'Bosna i Hercegovina',
	),
	array(
		'iso_3166_1_alpha2' => 'BW',
		'iso_3166_1_alpha3' => 'BWA',
		'iso_3166_1_numeric' => '072',
		'calling_code' => '267',
		'cctld' => 'bw',
		'name_english' => 'Botswana',
		'name_korean' => '보츠와나',
		'name_native' => 'Botswana',
	),
	array(
		'iso_3166_1_alpha2' => 'BV',
		'iso_3166_1_alpha3' => 'BVT',
		'iso_3166_1_numeric' => '074',
		'calling_code' => '',
		'cctld' => 'bv',
		'name_english' => 'Bouvet Island',
		'name_korean' => '부베 섬',
		'name_native' => 'Bouvet Island',
	),
	array(
		'iso_3166_1_alpha2' => 'BR',
		'iso_3166_1_alpha3' => 'BRA',
		'iso_3166_1_numeric' => '076',
		'calling_code' => '55',
		'cctld' => 'br',
		'name_english' => 'Brazil',
		'name_korean' => '브라질',
		'name_native' => 'Brasil',
	),
	array(
		'iso_3166_1_alpha2' => 'BZ',
		'iso_3166_1_alpha3' => 'BLZ',
		'iso_3166_1_numeric' => '084',
		'calling_code' => '501',
		'cctld' => 'bz',
		'name_english' => 'Belize',
		'name_korean' => '벨리즈',
		'name_native' => 'Belize',
	),
	array(
		'iso_3166_1_alpha2' => 'IO',
		'iso_3166_1_alpha3' => 'IOT',
		'iso_3166_1_numeric' => '086',
		'calling_code' => '246',
		'cctld' => 'io',
		'name_english' => 'British Indian Ocean Territory',
		'name_korean' => '영국령 인도양 지역',
		'name_native' => 'British Indian Ocean Territory',
	),
	array(
		'iso_3166_1_alpha2' => 'SB',
		'iso_3166_1_alpha3' => 'SLB',
		'iso_3166_1_numeric' => '090',
		'calling_code' => '677',
		'cctld' => 'sb',
		'name_english' => 'Solomon Islands',
		'name_korean' => '솔로몬 제도',
		'name_native' => 'Solomon Islands',
	),
	array(
		'iso_3166_1_alpha2' => 'VG',
		'iso_3166_1_alpha3' => 'VGB',
		'iso_3166_1_numeric' => '092',
		'calling_code' => '1-284',
		'cctld' => 'vg',
		'name_english' => 'Virgin Islands (British)',
		'name_korean' => '영국령 버진아일랜드',
		'name_native' => 'Virgin Islands (British)',
	),
	array(
		'iso_3166_1_alpha2' => 'BN',
		'iso_3166_1_alpha3' => 'BRN',
		'iso_3166_1_numeric' => '096',
		'calling_code' => '673',
		'cctld' => 'bn',
		'name_english' => 'Brunei',
		'name_korean' => '브루나이',
		'name_native' => 'بروني',
	),
	array(
		'iso_3166_1_alpha2' => 'BG',
		'iso_3166_1_alpha3' => 'BGR',
		'iso_3166_1_numeric' => '100',
		'calling_code' => '359',
		'cctld' => 'bg',
		'name_english' => 'Bulgaria',
		'name_korean' => '불가리아',
		'name_native' => 'Bulgariya',
	),
	array(
		'iso_3166_1_alpha2' => 'MM',
		'iso_3166_1_alpha3' => 'MMR',
		'iso_3166_1_numeric' => '104',
		'calling_code' => '95',
		'cctld' => 'mm',
		'name_english' => 'Myanmar',
		'name_korean' => '미얀마',
		'name_native' => 'Myanma',
	),
	array(
		'iso_3166_1_alpha2' => 'BI',
		'iso_3166_1_alpha3' => 'BDI',
		'iso_3166_1_numeric' => '108',
		'calling_code' => '257',
		'cctld' => 'bi',
		'name_english' => 'Burundi',
		'name_korean' => '부룬디',
		'name_native' => 'Burundi',
	),
	array(
		'iso_3166_1_alpha2' => 'BY',
		'iso_3166_1_alpha3' => 'BLR',
		'iso_3166_1_numeric' => '112',
		'calling_code' => '375',
		'cctld' => 'by',
		'name_english' => 'Belarus',
		'name_korean' => '벨라루스',
		'name_native' => 'Беларусь',
	),
	array(
		'iso_3166_1_alpha2' => 'KH',
		'iso_3166_1_alpha3' => 'KHM',
		'iso_3166_1_numeric' => '116',
		'calling_code' => '855',
		'cctld' => 'kh',
		'name_english' => 'Cambodia',
		'name_korean' => '캄보디아',
		'name_native' => 'កម្ពុជា',
	),
	array(
		'iso_3166_1_alpha2' => 'CM',
		'iso_3166_1_alpha3' => 'CMR',
		'iso_3166_1_numeric' => '120',
		'calling_code' => '237',
		'cctld' => 'cm',
		'name_english' => 'Cameroon',
		'name_korean' => '카메룬',
		'name_native' => 'Cameroun',
	),
	array(
		'iso_3166_1_alpha2' => 'CA',
		'iso_3166_1_alpha3' => 'CAN',
		'iso_3166_1_numeric' => '124',
		'calling_code' => '1',
		'cctld' => 'ca',
		'name_english' => 'Canada',
		'name_korean' => '캐나다',
		'name_native' => 'Canada',
	),
	array(
		'iso_3166_1_alpha2' => 'CV',
		'iso_3166_1_alpha3' => 'CPV',
		'iso_3166_1_numeric' => '132',
		'calling_code' => '238',
		'cctld' => 'cv',
		'name_english' => 'Cape Verde',
		'name_korean' => '카보베르데',
		'name_native' => 'Cabo Verde',
	),
	array(
		'iso_3166_1_alpha2' => 'KY',
		'iso_3166_1_alpha3' => 'CYM',
		'iso_3166_1_numeric' => '136',
		'calling_code' => '1-345',
		'cctld' => 'ky',
		'name_english' => 'Cayman Islands',
		'name_korean' => '케이맨 제도',
		'name_native' => 'Cayman Islands',
	),
	array(
		'iso_3166_1_alpha2' => 'CF',
		'iso_3166_1_alpha3' => 'CAF',
		'iso_3166_1_numeric' => '140',
		'calling_code' => '236',
		'cctld' => 'cf',
		'name_english' => 'Central African Republic',
		'name_korean' => '중앙아프리카 공화국',
		'name_native' => 'République Centrafricaine',
	),
	array(
		'iso_3166_1_alpha2' => 'LK',
		'iso_3166_1_alpha3' => 'LKA',
		'iso_3166_1_numeric' => '144',
		'calling_code' => '94',
		'cctld' => 'lk',
		'name_english' => 'Sri Lanka',
		'name_korean' => '스리랑카',
		'name_native' => 'ශ්‍රී ලංකාව, இலங்கை',
	),
	array(
		'iso_3166_1_alpha2' => 'TD',
		'iso_3166_1_alpha3' => 'TCD',
		'iso_3166_1_numeric' => '148',
		'calling_code' => '235',
		'cctld' => 'td',
		'name_english' => 'Chad',
		'name_korean' => '차드',
		'name_native' => 'Tchad',
	),
	array(
		'iso_3166_1_alpha2' => 'CL',
		'iso_3166_1_alpha3' => 'CHL',
		'iso_3166_1_numeric' => '152',
		'calling_code' => '56',
		'cctld' => 'cl',
		'name_english' => 'Chile',
		'name_korean' => '칠레',
		'name_native' => 'Chile',
	),
	array(
		'iso_3166_1_alpha2' => 'CN',
		'iso_3166_1_alpha3' => 'CHN',
		'iso_3166_1_numeric' => '156',
		'calling_code' => '86',
		'cctld' => 'cn',
		'name_english' => 'China',
		'name_korean' => '중국',
		'name_native' => '中国',
	),
	array(
		'iso_3166_1_alpha2' => 'TW',
		'iso_3166_1_alpha3' => 'TWN',
		'iso_3166_1_numeric' => '158',
		'calling_code' => '886',
		'cctld' => 'tw',
		'name_english' => 'Taiwan (Republic of China)',
		'name_korean' => '대만',
		'name_native' => '臺灣(中華民國)',
	),
	array(
		'iso_3166_1_alpha2' => 'CX',
		'iso_3166_1_alpha3' => 'CXR',
		'iso_3166_1_numeric' => '162',
		'calling_code' => '61',
		'cctld' => 'cx',
		'name_english' => 'Christmas Island',
		'name_korean' => '크리스마스 섬',
		'name_native' => 'Christmas Island',
	),
	array(
		'iso_3166_1_alpha2' => 'CC',
		'iso_3166_1_alpha3' => 'CCK',
		'iso_3166_1_numeric' => '166',
		'calling_code' => '61',
		'cctld' => 'cc',
		'name_english' => 'Cocos (Keeling) Islands',
		'name_korean' => '코코스 제도',
		'name_native' => 'Cocos (Keeling) Islands',
	),
	array(
		'iso_3166_1_alpha2' => 'CO',
		'iso_3166_1_alpha3' => 'COL',
		'iso_3166_1_numeric' => '170',
		'calling_code' => '57',
		'cctld' => 'co',
		'name_english' => 'Colombia',
		'name_korean' => '콜롬비아',
		'name_native' => 'Colombia',
	),
	array(
		'iso_3166_1_alpha2' => 'KM',
		'iso_3166_1_alpha3' => 'COM',
		'iso_3166_1_numeric' => '174',
		'calling_code' => '269',
		'cctld' => 'km',
		'name_english' => 'Comoros',
		'name_korean' => '코모로',
		'name_native' => 'Komori',
	),
	array(
		'iso_3166_1_alpha2' => 'YT',
		'iso_3166_1_alpha3' => 'MYT',
		'iso_3166_1_numeric' => '175',
		'calling_code' => '262',
		'cctld' => 'yt',
		'name_english' => 'Mayotte',
		'name_korean' => '마요트',
		'name_native' => 'Mayotte',
	),
	array(
		'iso_3166_1_alpha2' => 'CG',
		'iso_3166_1_alpha3' => 'COG',
		'iso_3166_1_numeric' => '178',
		'calling_code' => '242',
		'cctld' => 'cg',
		'name_english' => 'Congo (Republic of)',
		'name_korean' => '콩고',
		'name_native' => 'République du Congo',
	),
	array(
		'iso_3166_1_alpha2' => 'CD',
		'iso_3166_1_alpha3' => 'COD',
		'iso_3166_1_numeric' => '180',
		'calling_code' => '243',
		'cctld' => 'cd',
		'name_english' => 'Congo (Democratic Republic of the)',
		'name_korean' => '콩고 민주 공화국',
		'name_native' => 'République démocratique du Congo',
	),
	array(
		'iso_3166_1_alpha2' => 'CK',
		'iso_3166_1_alpha3' => 'COK',
		'iso_3166_1_numeric' => '184',
		'calling_code' => '682',
		'cctld' => 'ck',
		'name_english' => 'Cook Islands',
		'name_korean' => '쿡 제도',
		'name_native' => 'Cook Islands',
	),
	array(
		'iso_3166_1_alpha2' => 'CR',
		'iso_3166_1_alpha3' => 'CRI',
		'iso_3166_1_numeric' => '188',
		'calling_code' => '506',
		'cctld' => 'cr',
		'name_english' => 'Costa Rica',
		'name_korean' => '코스타리카',
		'name_native' => 'Costa Rica',
	),
	array(
		'iso_3166_1_alpha2' => 'HR',
		'iso_3166_1_alpha3' => 'HRV',
		'iso_3166_1_numeric' => '191',
		'calling_code' => '385',
		'cctld' => 'hr',
		'name_english' => 'Croatia',
		'name_korean' => '크로아티아',
		'name_native' => 'Hrvatska',
	),
	array(
		'iso_3166_1_alpha2' => 'CU',
		'iso_3166_1_alpha3' => 'CUB',
		'iso_3166_1_numeric' => '192',
		'calling_code' => '53',
		'cctld' => 'cu',
		'name_english' => 'Cuba',
		'name_korean' => '쿠바',
		'name_native' => 'Cuba',
	),
	array(
		'iso_3166_1_alpha2' => 'CY',
		'iso_3166_1_alpha3' => 'CYP',
		'iso_3166_1_numeric' => '196',
		'calling_code' => '357',
		'cctld' => 'cy',
		'name_english' => 'Cyprus',
		'name_korean' => '키프로스',
		'name_native' => 'Κύπρος',
	),
	array(
		'iso_3166_1_alpha2' => 'CZ',
		'iso_3166_1_alpha3' => 'CZE',
		'iso_3166_1_numeric' => '203',
		'calling_code' => '420',
		'cctld' => 'cz',
		'name_english' => 'Czech Republic',
		'name_korean' => '체코',
		'name_native' => 'Česká republika',
	),
	array(
		'iso_3166_1_alpha2' => 'BJ',
		'iso_3166_1_alpha3' => 'BEN',
		'iso_3166_1_numeric' => '204',
		'calling_code' => '229',
		'cctld' => 'bj',
		'name_english' => 'Benin',
		'name_korean' => '베냉',
		'name_native' => 'Bénin',
	),
	array(
		'iso_3166_1_alpha2' => 'DK',
		'iso_3166_1_alpha3' => 'DNK',
		'iso_3166_1_numeric' => '208',
		'calling_code' => '45',
		'cctld' => 'dk',
		'name_english' => 'Denmark',
		'name_korean' => '덴마크',
		'name_native' => 'Danmark',
	),
	array(
		'iso_3166_1_alpha2' => 'DM',
		'iso_3166_1_alpha3' => 'DMA',
		'iso_3166_1_numeric' => '212',
		'calling_code' => '1-767',
		'cctld' => 'dm',
		'name_english' => 'Dominica',
		'name_korean' => '도미니카 연방',
		'name_native' => 'Dominica',
	),
	array(
		'iso_3166_1_alpha2' => 'DO',
		'iso_3166_1_alpha3' => 'DOM',
		'iso_3166_1_numeric' => '214',
		'calling_code' => '1',
		'cctld' => 'do',
		'name_english' => 'Dominican Republic',
		'name_korean' => '도미니카 공화국',
		'name_native' => 'República Dominicana',
	),
	array(
		'iso_3166_1_alpha2' => 'EC',
		'iso_3166_1_alpha3' => 'ECU',
		'iso_3166_1_numeric' => '218',
		'calling_code' => '593',
		'cctld' => 'ec',
		'name_english' => 'Ecuador',
		'name_korean' => '에콰도르',
		'name_native' => 'Ecuador',
	),
	array(
		'iso_3166_1_alpha2' => 'SV',
		'iso_3166_1_alpha3' => 'SLV',
		'iso_3166_1_numeric' => '222',
		'calling_code' => '503',
		'cctld' => 'sv',
		'name_english' => 'El Salvador',
		'name_korean' => '엘살바도르',
		'name_native' => 'El Salvador',
	),
	array(
		'iso_3166_1_alpha2' => 'GQ',
		'iso_3166_1_alpha3' => 'GNQ',
		'iso_3166_1_numeric' => '226',
		'calling_code' => '240',
		'cctld' => 'gq',
		'name_english' => 'Equatorial Guinea',
		'name_korean' => '적도기니',
		'name_native' => 'Guinea Ecuatorial',
	),
	array(
		'iso_3166_1_alpha2' => 'ET',
		'iso_3166_1_alpha3' => 'ETH',
		'iso_3166_1_numeric' => '231',
		'calling_code' => '251',
		'cctld' => 'et',
		'name_english' => 'Ethiopia',
		'name_korean' => '에티오피아',
		'name_native' => 'ኢትዮጵያ',
	),
	array(
		'iso_3166_1_alpha2' => 'ER',
		'iso_3166_1_alpha3' => 'ERI',
		'iso_3166_1_numeric' => '232',
		'calling_code' => '291',
		'cctld' => 'er',
		'name_english' => 'Eritrea',
		'name_korean' => '에리트레아',
		'name_native' => 'إرتريا',
	),
	array(
		'iso_3166_1_alpha2' => 'EE',
		'iso_3166_1_alpha3' => 'EST',
		'iso_3166_1_numeric' => '233',
		'calling_code' => '372',
		'cctld' => 'ee',
		'name_english' => 'Estonia',
		'name_korean' => '에스토니아',
		'name_native' => 'Eesti',
	),
	array(
		'iso_3166_1_alpha2' => 'FO',
		'iso_3166_1_alpha3' => 'FRO',
		'iso_3166_1_numeric' => '234',
		'calling_code' => '298',
		'cctld' => 'fo',
		'name_english' => 'Faroe Islands',
		'name_korean' => '페로 제도',
		'name_native' => 'Føroyar',
	),
	array(
		'iso_3166_1_alpha2' => 'FK',
		'iso_3166_1_alpha3' => 'FLK',
		'iso_3166_1_numeric' => '238',
		'calling_code' => '500',
		'cctld' => 'fk',
		'name_english' => 'Falkland Islands (Malvinas)',
		'name_korean' => '포클랜드 제도',
		'name_native' => 'Falkland Islands (Malvinas)',
	),
	array(
		'iso_3166_1_alpha2' => 'GS',
		'iso_3166_1_alpha3' => 'SGS',
		'iso_3166_1_numeric' => '239',
		'calling_code' => '',
		'cctld' => 'gs',
		'name_english' => 'South Georgia and the South Sandwich Islands',
		'name_korean' => '사우스조지아 사우스샌드위치 제도',
		'name_native' => 'South Georgia and the South Sandwich Islands',
	),
	array(
		'iso_3166_1_alpha2' => 'FJ',
		'iso_3166_1_alpha3' => 'FJI',
		'iso_3166_1_numeric' => '242',
		'calling_code' => '679',
		'cctld' => 'fj',
		'name_english' => 'Fiji',
		'name_korean' => '피지',
		'name_native' => 'Fiji',
	),
	array(
		'iso_3166_1_alpha2' => 'FI',
		'iso_3166_1_alpha3' => 'FIN',
		'iso_3166_1_numeric' => '246',
		'calling_code' => '358',
		'cctld' => 'fi',
		'name_english' => 'Finland',
		'name_korean' => '핀란드',
		'name_native' => 'Suomi',
	),
	array(
		'iso_3166_1_alpha2' => 'AX',
		'iso_3166_1_alpha3' => 'ALA',
		'iso_3166_1_numeric' => '248',
		'calling_code' => '',
		'cctld' => 'ax',
		'name_english' => 'Åland Islands',
		'name_korean' => '올란드 제도',
		'name_native' => 'Åland Islands',
	),
	array(
		'iso_3166_1_alpha2' => 'FR',
		'iso_3166_1_alpha3' => 'FRA',
		'iso_3166_1_numeric' => '250',
		'calling_code' => '33',
		'cctld' => 'fr',
		'name_english' => 'France',
		'name_korean' => '프랑스',
		'name_native' => 'France',
	),
	array(
		'iso_3166_1_alpha2' => 'GF',
		'iso_3166_1_alpha3' => 'GUF',
		'iso_3166_1_numeric' => '254',
		'calling_code' => '594',
		'cctld' => 'gf',
		'name_english' => 'French Guiana',
		'name_korean' => '프랑스령 기아나',
		'name_native' => 'Guyane',
	),
	array(
		'iso_3166_1_alpha2' => 'PF',
		'iso_3166_1_alpha3' => 'PYF',
		'iso_3166_1_numeric' => '258',
		'calling_code' => '689',
		'cctld' => 'pf',
		'name_english' => 'French Polynesia',
		'name_korean' => '프랑스령 폴리네시아',
		'name_native' => 'Polynésie française',
	),
	array(
		'iso_3166_1_alpha2' => 'TF',
		'iso_3166_1_alpha3' => 'ATF',
		'iso_3166_1_numeric' => '260',
		'calling_code' => '',
		'cctld' => 'tf',
		'name_english' => 'French Southern and Antarctic Lands',
		'name_korean' => '프랑스령 남방 및 남극 지역',
		'name_native' => 'Terres australes et antarctiques françaises',
	),
	array(
		'iso_3166_1_alpha2' => 'DJ',
		'iso_3166_1_alpha3' => 'DJI',
		'iso_3166_1_numeric' => '262',
		'calling_code' => '253',
		'cctld' => 'dj',
		'name_english' => 'Djibouti',
		'name_korean' => '지부티',
		'name_native' => 'جيبوتي',
	),
	array(
		'iso_3166_1_alpha2' => 'GA',
		'iso_3166_1_alpha3' => 'GAB',
		'iso_3166_1_numeric' => '266',
		'calling_code' => '241',
		'cctld' => 'ga',
		'name_english' => 'Gabon',
		'name_korean' => '가봉',
		'name_native' => 'Gabon',
	),
	array(
		'iso_3166_1_alpha2' => 'GE',
		'iso_3166_1_alpha3' => 'GEO',
		'iso_3166_1_numeric' => '268',
		'calling_code' => '995',
		'cctld' => 'ge',
		'name_english' => 'Georgia',
		'name_korean' => '그루지아',
		'name_native' => 'საქართველო',
	),
	array(
		'iso_3166_1_alpha2' => 'GM',
		'iso_3166_1_alpha3' => 'GMB',
		'iso_3166_1_numeric' => '270',
		'calling_code' => '220',
		'cctld' => 'gm',
		'name_english' => 'Gambia',
		'name_korean' => '감비아',
		'name_native' => 'Gambia',
	),
	array(
		'iso_3166_1_alpha2' => 'PS',
		'iso_3166_1_alpha3' => 'PSE',
		'iso_3166_1_numeric' => '275',
		'calling_code' => '970',
		'cctld' => 'ps',
		'name_english' => 'Palestine',
		'name_korean' => '팔레스타인',
		'name_native' => 'فلسطين',
	),
	array(
		'iso_3166_1_alpha2' => 'DE',
		'iso_3166_1_alpha3' => 'DEU',
		'iso_3166_1_numeric' => '276',
		'calling_code' => '49',
		'cctld' => 'de',
		'name_english' => 'Germany',
		'name_korean' => '독일',
		'name_native' => 'Deutschland',
	),
	array(
		'iso_3166_1_alpha2' => 'GH',
		'iso_3166_1_alpha3' => 'GHA',
		'iso_3166_1_numeric' => '288',
		'calling_code' => '233',
		'cctld' => 'gh',
		'name_english' => 'Ghana',
		'name_korean' => '가나',
		'name_native' => 'Ghana',
	),
	array(
		'iso_3166_1_alpha2' => 'GI',
		'iso_3166_1_alpha3' => 'GIB',
		'iso_3166_1_numeric' => '292',
		'calling_code' => '350',
		'cctld' => 'gi',
		'name_english' => 'Gibraltar',
		'name_korean' => '지브롤터',
		'name_native' => 'Gibraltar',
	),
	array(
		'iso_3166_1_alpha2' => 'KI',
		'iso_3166_1_alpha3' => 'KIR',
		'iso_3166_1_numeric' => '296',
		'calling_code' => '686',
		'cctld' => 'ki',
		'name_english' => 'Kiribati',
		'name_korean' => '키리바시',
		'name_native' => 'Kiribati',
	),
	array(
		'iso_3166_1_alpha2' => 'GR',
		'iso_3166_1_alpha3' => 'GRC',
		'iso_3166_1_numeric' => '300',
		'calling_code' => '30',
		'cctld' => 'gr',
		'name_english' => 'Greece',
		'name_korean' => '그리스',
		'name_native' => 'Ελλάς',
	),
	array(
		'iso_3166_1_alpha2' => 'GL',
		'iso_3166_1_alpha3' => 'GRL',
		'iso_3166_1_numeric' => '304',
		'calling_code' => '299',
		'cctld' => 'gl',
		'name_english' => 'Greenland',
		'name_korean' => '그린란드',
		'name_native' => 'Grønland, Kalaallit Nunaat',
	),
	array(
		'iso_3166_1_alpha2' => 'GD',
		'iso_3166_1_alpha3' => 'GRD',
		'iso_3166_1_numeric' => '308',
		'calling_code' => '1-473',
		'cctld' => 'gd',
		'name_english' => 'Grenada',
		'name_korean' => '그레나다',
		'name_native' => 'Grenada',
	),
	array(
		'iso_3166_1_alpha2' => 'GP',
		'iso_3166_1_alpha3' => 'GLP',
		'iso_3166_1_numeric' => '312',
		'calling_code' => '590',
		'cctld' => 'gp',
		'name_english' => 'Guadeloupe',
		'name_korean' => '과들루프',
		'name_native' => 'Guadeloupe',
	),
	array(
		'iso_3166_1_alpha2' => 'GU',
		'iso_3166_1_alpha3' => 'GUM',
		'iso_3166_1_numeric' => '316',
		'calling_code' => '1-671',
		'cctld' => 'gu',
		'name_english' => 'Guam',
		'name_korean' => '괌',
		'name_native' => 'Guam, Guåhån',
	),
	array(
		'iso_3166_1_alpha2' => 'GT',
		'iso_3166_1_alpha3' => 'GTM',
		'iso_3166_1_numeric' => '320',
		'calling_code' => '502',
		'cctld' => 'gt',
		'name_english' => 'Guatemala',
		'name_korean' => '과테말라',
		'name_native' => 'Guatemala',
	),
	array(
		'iso_3166_1_alpha2' => 'GN',
		'iso_3166_1_alpha3' => 'GIN',
		'iso_3166_1_numeric' => '324',
		'calling_code' => '224',
		'cctld' => 'gn',
		'name_english' => 'Guinea',
		'name_korean' => '기니',
		'name_native' => 'Guinée, Gine',
	),
	array(
		'iso_3166_1_alpha2' => 'GY',
		'iso_3166_1_alpha3' => 'GUY',
		'iso_3166_1_numeric' => '328',
		'calling_code' => '592',
		'cctld' => 'gy',
		'name_english' => 'Guyana',
		'name_korean' => '가이아나',
		'name_native' => 'Guyana',
	),
	array(
		'iso_3166_1_alpha2' => 'HT',
		'iso_3166_1_alpha3' => 'HTI',
		'iso_3166_1_numeric' => '332',
		'calling_code' => '509',
		'cctld' => 'ht',
		'name_english' => 'Haiti',
		'name_korean' => '아이티',
		'name_native' => 'Haïti, Ayiti',
	),
	array(
		'iso_3166_1_alpha2' => 'HM',
		'iso_3166_1_alpha3' => 'HMD',
		'iso_3166_1_numeric' => '334',
		'calling_code' => '',
		'cctld' => 'hm',
		'name_english' => 'Heard Island and McDonald Islands',
		'name_korean' => '허드 맥도널드 제도',
		'name_native' => 'Heard Island and McDonald Islands',
	),
	array(
		'iso_3166_1_alpha2' => 'VA',
		'iso_3166_1_alpha3' => 'VAT',
		'iso_3166_1_numeric' => '336',
		'calling_code' => '379',
		'cctld' => 'va',
		'name_english' => 'Vatican City',
		'name_korean' => '바티칸',
		'name_native' => 'E Civitate Vaticana',
	),
	array(
		'iso_3166_1_alpha2' => 'HN',
		'iso_3166_1_alpha3' => 'HND',
		'iso_3166_1_numeric' => '340',
		'calling_code' => '504',
		'cctld' => 'hn',
		'name_english' => 'Honduras',
		'name_korean' => '온두라스',
		'name_native' => 'Honduras',
	),
	array(
		'iso_3166_1_alpha2' => 'HK',
		'iso_3166_1_alpha3' => 'HKG',
		'iso_3166_1_numeric' => '344',
		'calling_code' => '852',
		'cctld' => 'hk',
		'name_english' => 'Hong Kong',
		'name_korean' => '홍콩',
		'name_native' => '香港',
	),
	array(
		'iso_3166_1_alpha2' => 'HU',
		'iso_3166_1_alpha3' => 'HUN',
		'iso_3166_1_numeric' => '348',
		'calling_code' => '36',
		'cctld' => 'hu',
		'name_english' => 'Hungary',
		'name_korean' => '헝가리',
		'name_native' => 'Magyarország',
	),
	array(
		'iso_3166_1_alpha2' => 'IS',
		'iso_3166_1_alpha3' => 'ISL',
		'iso_3166_1_numeric' => '352',
		'calling_code' => '354',
		'cctld' => 'is',
		'name_english' => 'Iceland',
		'name_korean' => '아이슬란드',
		'name_native' => 'Ísland',
	),
	array(
		'iso_3166_1_alpha2' => 'IN',
		'iso_3166_1_alpha3' => 'IND',
		'iso_3166_1_numeric' => '356',
		'calling_code' => '91',
		'cctld' => 'in',
		'name_english' => 'India',
		'name_korean' => '인도',
		'name_native' => 'Bhārat Gaṇarājya, भारत, ভারত',
	),
	array(
		'iso_3166_1_alpha2' => 'ID',
		'iso_3166_1_alpha3' => 'IDN',
		'iso_3166_1_numeric' => '360',
		'calling_code' => '62',
		'cctld' => 'id',
		'name_english' => 'Indonesia',
		'name_korean' => '인도네시아',
		'name_native' => 'Indonesia',
	),
	array(
		'iso_3166_1_alpha2' => 'IR',
		'iso_3166_1_alpha3' => 'IRN',
		'iso_3166_1_numeric' => '364',
		'calling_code' => '98',
		'cctld' => 'ir',
		'name_english' => 'Iran',
		'name_korean' => '이란',
		'name_native' => 'ایران',
	),
	array(
		'iso_3166_1_alpha2' => 'IQ',
		'iso_3166_1_alpha3' => 'IRQ',
		'iso_3166_1_numeric' => '368',
		'calling_code' => '964',
		'cctld' => 'iq',
		'name_english' => 'Iraq',
		'name_korean' => '이라크',
		'name_native' => 'العراق',
	),
	array(
		'iso_3166_1_alpha2' => 'IE',
		'iso_3166_1_alpha3' => 'IRL',
		'iso_3166_1_numeric' => '372',
		'calling_code' => '353',
		'cctld' => 'ie',
		'name_english' => 'Ireland',
		'name_korean' => '아일랜드',
		'name_native' => 'Éire',
	),
	array(
		'iso_3166_1_alpha2' => 'IL',
		'iso_3166_1_alpha3' => 'ISR',
		'iso_3166_1_numeric' => '376',
		'calling_code' => '972',
		'cctld' => 'il',
		'name_english' => 'Israel',
		'name_korean' => '이스라엘',
		'name_native' => 'ישראל',
	),
	array(
		'iso_3166_1_alpha2' => 'IT',
		'iso_3166_1_alpha3' => 'ITA',
		'iso_3166_1_numeric' => '380',
		'calling_code' => '39',
		'cctld' => 'it',
		'name_english' => 'Italy',
		'name_korean' => '이탈리아',
		'name_native' => 'Italia',
	),
	array(
		'iso_3166_1_alpha2' => 'CI',
		'iso_3166_1_alpha3' => 'CIV',
		'iso_3166_1_numeric' => '384',
		'calling_code' => '225',
		'cctld' => 'ci',
		'name_english' => 'Ivory Coast',
		'name_korean' => '코트디부아르',
		'name_native' => 'Côte d\'Ivoire',
	),
	array(
		'iso_3166_1_alpha2' => 'JM',
		'iso_3166_1_alpha3' => 'JAM',
		'iso_3166_1_numeric' => '388',
		'calling_code' => '1-876',
		'cctld' => 'jm',
		'name_english' => 'Jamaica',
		'name_korean' => '자메이카',
		'name_native' => 'Jamaica',
	),
	array(
		'iso_3166_1_alpha2' => 'JP',
		'iso_3166_1_alpha3' => 'JPN',
		'iso_3166_1_numeric' => '392',
		'calling_code' => '81',
		'cctld' => 'jp',
		'name_english' => 'Japan',
		'name_korean' => '일본',
		'name_native' => '日本',
	),
	array(
		'iso_3166_1_alpha2' => 'KZ',
		'iso_3166_1_alpha3' => 'KAZ',
		'iso_3166_1_numeric' => '398',
		'calling_code' => '7',
		'cctld' => 'kz',
		'name_english' => 'Kazakhstan',
		'name_korean' => '카자흐스탄',
		'name_native' => 'Қазақстан',
	),
	array(
		'iso_3166_1_alpha2' => 'JO',
		'iso_3166_1_alpha3' => 'JOR',
		'iso_3166_1_numeric' => '400',
		'calling_code' => '962',
		'cctld' => 'jo',
		'name_english' => 'Jordan',
		'name_korean' => '요르단',
		'name_native' => 'الأردن',
	),
	array(
		'iso_3166_1_alpha2' => 'KE',
		'iso_3166_1_alpha3' => 'KEN',
		'iso_3166_1_numeric' => '404',
		'calling_code' => '254',
		'cctld' => 'ke',
		'name_english' => 'Kenya',
		'name_korean' => '케냐',
		'name_native' => 'Kenya',
	),
	array(
		'iso_3166_1_alpha2' => 'KP',
		'iso_3166_1_alpha3' => 'PRK',
		'iso_3166_1_numeric' => '408',
		'calling_code' => '850',
		'cctld' => 'kp',
		'name_english' => 'Korea (Democratic People\'s Republic of)',
		'name_korean' => '북한',
		'name_native' => '조선민주주의인민공화국',
	),
	array(
		'iso_3166_1_alpha2' => 'KR',
		'iso_3166_1_alpha3' => 'KOR',
		'iso_3166_1_numeric' => '410',
		'calling_code' => '82',
		'cctld' => 'kr',
		'name_english' => 'Korea (Republic of)',
		'name_korean' => '대한민국',
		'name_native' => '대한민국',
	),
	array(
		'iso_3166_1_alpha2' => 'KW',
		'iso_3166_1_alpha3' => 'KWT',
		'iso_3166_1_numeric' => '414',
		'calling_code' => '965',
		'cctld' => 'kw',
		'name_english' => 'Kuwait',
		'name_korean' => '쿠웨이트',
		'name_native' => 'دولة الكويت',
	),
	array(
		'iso_3166_1_alpha2' => 'KG',
		'iso_3166_1_alpha3' => 'KGZ',
		'iso_3166_1_numeric' => '417',
		'calling_code' => '996',
		'cctld' => 'kg',
		'name_english' => 'Kyrgyzstan',
		'name_korean' => '키르기스스탄',
		'name_native' => 'Кыргызстан',
	),
	array(
		'iso_3166_1_alpha2' => 'LA',
		'iso_3166_1_alpha3' => 'LAO',
		'iso_3166_1_numeric' => '418',
		'calling_code' => '856',
		'cctld' => 'la',
		'name_english' => 'Laos',
		'name_korean' => '라오스',
		'name_native' => 'ປະເທດລາວ',
	),
	array(
		'iso_3166_1_alpha2' => 'LB',
		'iso_3166_1_alpha3' => 'LBN',
		'iso_3166_1_numeric' => '422',
		'calling_code' => '961',
		'cctld' => 'lb',
		'name_english' => 'Lebanon',
		'name_korean' => '레바논',
		'name_native' => 'لبنان',
	),
	array(
		'iso_3166_1_alpha2' => 'LS',
		'iso_3166_1_alpha3' => 'LSO',
		'iso_3166_1_numeric' => '426',
		'calling_code' => '266',
		'cctld' => 'ls',
		'name_english' => 'Lesotho',
		'name_korean' => '레소토',
		'name_native' => 'Lesotho',
	),
	array(
		'iso_3166_1_alpha2' => 'LV',
		'iso_3166_1_alpha3' => 'LVA',
		'iso_3166_1_numeric' => '428',
		'calling_code' => '371',
		'cctld' => 'lv',
		'name_english' => 'Latvia',
		'name_korean' => '라트비아',
		'name_native' => 'Latvija',
	),
	array(
		'iso_3166_1_alpha2' => 'LR',
		'iso_3166_1_alpha3' => 'LBR',
		'iso_3166_1_numeric' => '430',
		'calling_code' => '231',
		'cctld' => 'lr',
		'name_english' => 'Liberia',
		'name_korean' => '라이베리아',
		'name_native' => 'Liberia',
	),
	array(
		'iso_3166_1_alpha2' => 'LY',
		'iso_3166_1_alpha3' => 'LBY',
		'iso_3166_1_numeric' => '434',
		'calling_code' => '218',
		'cctld' => 'ly',
		'name_english' => 'Libya',
		'name_korean' => '리비아',
		'name_native' => 'ليبيا',
	),
	array(
		'iso_3166_1_alpha2' => 'LI',
		'iso_3166_1_alpha3' => 'LIE',
		'iso_3166_1_numeric' => '438',
		'calling_code' => '423',
		'cctld' => 'li',
		'name_english' => 'Liechtenstein',
		'name_korean' => '리히텐슈타인',
		'name_native' => 'Liechtenstein',
	),
	array(
		'iso_3166_1_alpha2' => 'LT',
		'iso_3166_1_alpha3' => 'LTU',
		'iso_3166_1_numeric' => '440',
		'calling_code' => '370',
		'cctld' => 'lt',
		'name_english' => 'Lithuania',
		'name_korean' => '리투아니아',
		'name_native' => 'Lietuva',
	),
	array(
		'iso_3166_1_alpha2' => 'LU',
		'iso_3166_1_alpha3' => 'LUX',
		'iso_3166_1_numeric' => '442',
		'calling_code' => '352',
		'cctld' => 'lu',
		'name_english' => 'Luxembourg',
		'name_korean' => '룩셈부르크',
		'name_native' => 'Lëtzebuerg',
	),
	array(
		'iso_3166_1_alpha2' => 'MO',
		'iso_3166_1_alpha3' => 'MAC',
		'iso_3166_1_numeric' => '446',
		'calling_code' => '853',
		'cctld' => 'mo',
		'name_english' => 'Macau',
		'name_korean' => '마카오',
		'name_native' => '澳門',
	),
	array(
		'iso_3166_1_alpha2' => 'MG',
		'iso_3166_1_alpha3' => 'MDG',
		'iso_3166_1_numeric' => '450',
		'calling_code' => '261',
		'cctld' => 'mg',
		'name_english' => 'Madagascar',
		'name_korean' => '마다가스카',
		'name_native' => 'Madagasikara',
	),
	array(
		'iso_3166_1_alpha2' => 'MW',
		'iso_3166_1_alpha3' => 'MWI',
		'iso_3166_1_numeric' => '454',
		'calling_code' => '265',
		'cctld' => 'mw',
		'name_english' => 'Malawi',
		'name_korean' => '말라위',
		'name_native' => 'Malawi',
	),
	array(
		'iso_3166_1_alpha2' => 'MY',
		'iso_3166_1_alpha3' => 'MYS',
		'iso_3166_1_numeric' => '458',
		'calling_code' => '60',
		'cctld' => 'my',
		'name_english' => 'Malaysia',
		'name_korean' => '말레이시아',
		'name_native' => 'Malaysia',
	),
	array(
		'iso_3166_1_alpha2' => 'MV',
		'iso_3166_1_alpha3' => 'MDV',
		'iso_3166_1_numeric' => '462',
		'calling_code' => '960',
		'cctld' => 'mv',
		'name_english' => 'Maldives',
		'name_korean' => '몰디브',
		'name_native' => 'ދިވެހިރާއްޖެ',
	),
	array(
		'iso_3166_1_alpha2' => 'ML',
		'iso_3166_1_alpha3' => 'MLI',
		'iso_3166_1_numeric' => '466',
		'calling_code' => '223',
		'cctld' => 'ml',
		'name_english' => 'Mali',
		'name_korean' => '말리',
		'name_native' => 'Mali',
	),
	array(
		'iso_3166_1_alpha2' => 'MT',
		'iso_3166_1_alpha3' => 'MLT',
		'iso_3166_1_numeric' => '470',
		'calling_code' => '356',
		'cctld' => 'mt',
		'name_english' => 'Malta',
		'name_korean' => '몰타',
		'name_native' => 'Malta',
	),
	array(
		'iso_3166_1_alpha2' => 'MQ',
		'iso_3166_1_alpha3' => 'MTQ',
		'iso_3166_1_numeric' => '474',
		'calling_code' => '596',
		'cctld' => 'mq',
		'name_english' => 'Martinique',
		'name_korean' => '마르티니크',
		'name_native' => 'Martinique',
	),
	array(
		'iso_3166_1_alpha2' => 'MR',
		'iso_3166_1_alpha3' => 'MRT',
		'iso_3166_1_numeric' => '478',
		'calling_code' => '222',
		'cctld' => 'mr',
		'name_english' => 'Mauritania',
		'name_korean' => '모리타니',
		'name_native' => 'موريتانيا',
	),
	array(
		'iso_3166_1_alpha2' => 'MU',
		'iso_3166_1_alpha3' => 'MUS',
		'iso_3166_1_numeric' => '480',
		'calling_code' => '230',
		'cctld' => 'mu',
		'name_english' => 'Mauritius',
		'name_korean' => '모리셔스',
		'name_native' => 'Maurice',
	),
	array(
		'iso_3166_1_alpha2' => 'MX',
		'iso_3166_1_alpha3' => 'MEX',
		'iso_3166_1_numeric' => '484',
		'calling_code' => '52',
		'cctld' => 'mx',
		'name_english' => 'Mexico',
		'name_korean' => '멕시코',
		'name_native' => 'México',
	),
	array(
		'iso_3166_1_alpha2' => 'MC',
		'iso_3166_1_alpha3' => 'MCO',
		'iso_3166_1_numeric' => '492',
		'calling_code' => '377',
		'cctld' => 'mc',
		'name_english' => 'Monaco',
		'name_korean' => '모나코',
		'name_native' => 'Monaco',
	),
	array(
		'iso_3166_1_alpha2' => 'MN',
		'iso_3166_1_alpha3' => 'MNG',
		'iso_3166_1_numeric' => '496',
		'calling_code' => '976',
		'cctld' => 'mn',
		'name_english' => 'Mongolia',
		'name_korean' => '몽골',
		'name_native' => 'Монгол Улс',
	),
	array(
		'iso_3166_1_alpha2' => 'MD',
		'iso_3166_1_alpha3' => 'MDA',
		'iso_3166_1_numeric' => '498',
		'calling_code' => '373',
		'cctld' => 'md',
		'name_english' => 'Moldova (Republic of)',
		'name_korean' => '몰도바',
		'name_native' => 'Moldova',
	),
	array(
		'iso_3166_1_alpha2' => 'ME',
		'iso_3166_1_alpha3' => 'MNE',
		'iso_3166_1_numeric' => '499',
		'calling_code' => '382',
		'cctld' => 'me',
		'name_english' => 'Montenegro',
		'name_korean' => '몬테네그로',
		'name_native' => 'Црна Гора',
	),
	array(
		'iso_3166_1_alpha2' => 'MS',
		'iso_3166_1_alpha3' => 'MSR',
		'iso_3166_1_numeric' => '500',
		'calling_code' => '1-664',
		'cctld' => 'ms',
		'name_english' => 'Montserrat',
		'name_korean' => '몬트세랫',
		'name_native' => 'Montserrat',
	),
	array(
		'iso_3166_1_alpha2' => 'MA',
		'iso_3166_1_alpha3' => 'MAR',
		'iso_3166_1_numeric' => '504',
		'calling_code' => '212',
		'cctld' => 'ma',
		'name_english' => 'Morocco',
		'name_korean' => '모로코',
		'name_native' => 'المغرب',
	),
	array(
		'iso_3166_1_alpha2' => 'MZ',
		'iso_3166_1_alpha3' => 'MOZ',
		'iso_3166_1_numeric' => '508',
		'calling_code' => '258',
		'cctld' => 'mz',
		'name_english' => 'Mozambique',
		'name_korean' => '모잠비크',
		'name_native' => 'Moçambique',
	),
	array(
		'iso_3166_1_alpha2' => 'OM',
		'iso_3166_1_alpha3' => 'OMN',
		'iso_3166_1_numeric' => '512',
		'calling_code' => '968',
		'cctld' => 'om',
		'name_english' => 'Oman',
		'name_korean' => '오만',
		'name_native' => 'عُمان',
	),
	array(
		'iso_3166_1_alpha2' => 'NA',
		'iso_3166_1_alpha3' => 'NAM',
		'iso_3166_1_numeric' => '516',
		'calling_code' => '264',
		'cctld' => 'na',
		'name_english' => 'Namibia',
		'name_korean' => '나미비아',
		'name_native' => 'Namibia',
	),
	array(
		'iso_3166_1_alpha2' => 'NR',
		'iso_3166_1_alpha3' => 'NRU',
		'iso_3166_1_numeric' => '520',
		'calling_code' => '674',
		'cctld' => 'nr',
		'name_english' => 'Nauru',
		'name_korean' => '나우루',
		'name_native' => 'Naoero',
	),
	array(
		'iso_3166_1_alpha2' => 'NP',
		'iso_3166_1_alpha3' => 'NPL',
		'iso_3166_1_numeric' => '524',
		'calling_code' => '977',
		'cctld' => 'np',
		'name_english' => 'Nepal',
		'name_korean' => '네팔',
		'name_native' => 'नेपाल',
	),
	array(
		'iso_3166_1_alpha2' => 'NL',
		'iso_3166_1_alpha3' => 'NLD',
		'iso_3166_1_numeric' => '528',
		'calling_code' => '31',
		'cctld' => 'nl',
		'name_english' => 'Netherlands',
		'name_korean' => '네덜란드',
		'name_native' => 'Nederland',
	),
	array(
		'iso_3166_1_alpha2' => 'AN',
		'iso_3166_1_alpha3' => 'ANT',
		'iso_3166_1_numeric' => '530',
		'calling_code' => '599',
		'cctld' => 'an',
		'name_english' => 'Netherlands Antilles',
		'name_korean' => '네덜란드령 안틸레스',
		'name_native' => 'Nederlandse Antillen',
	),
	array(
		'iso_3166_1_alpha2' => 'CW',
		'iso_3166_1_alpha3' => 'CUW',
		'iso_3166_1_numeric' => '531',
		'calling_code' => '599',
		'cctld' => 'cw',
		'name_english' => 'Curaçao',
		'name_korean' => '퀴라소',
		'name_native' => 'Curaçao',
	),
	array(
		'iso_3166_1_alpha2' => 'AW',
		'iso_3166_1_alpha3' => 'ABW',
		'iso_3166_1_numeric' => '533',
		'calling_code' => '297',
		'cctld' => 'aw',
		'name_english' => 'Aruba',
		'name_korean' => '아루바',
		'name_native' => 'Aruba',
	),
	array(
		'iso_3166_1_alpha2' => 'SX',
		'iso_3166_1_alpha3' => 'SXM',
		'iso_3166_1_numeric' => '534',
		'calling_code' => '1-721',
		'cctld' => 'sx',
		'name_english' => 'Sint Maarten (Dutch)',
		'name_korean' => '신트마르턴 (네덜란드령)',
		'name_native' => 'Sint Maarten',
	),
	array(
		'iso_3166_1_alpha2' => 'BQ',
		'iso_3166_1_alpha3' => 'BES',
		'iso_3166_1_numeric' => '535',
		'calling_code' => '599',
		'cctld' => 'bq',
		'name_english' => 'Caribbean Netherlands',
		'name_korean' => '네덜란드령 카리브',
		'name_native' => 'Caribisch Nederland',
	),
	array(
		'iso_3166_1_alpha2' => 'NC',
		'iso_3166_1_alpha3' => 'NCL',
		'iso_3166_1_numeric' => '540',
		'calling_code' => '687',
		'cctld' => 'nc',
		'name_english' => 'New Caledonia',
		'name_korean' => '누벨칼레도니',
		'name_native' => 'Nouvelle-Calédonie',
	),
	array(
		'iso_3166_1_alpha2' => 'VU',
		'iso_3166_1_alpha3' => 'VUT',
		'iso_3166_1_numeric' => '548',
		'calling_code' => '678',
		'cctld' => 'vu',
		'name_english' => 'Vanuatu',
		'name_korean' => '바누아투',
		'name_native' => 'Vanuatu',
	),
	array(
		'iso_3166_1_alpha2' => 'NZ',
		'iso_3166_1_alpha3' => 'NZL',
		'iso_3166_1_numeric' => '554',
		'calling_code' => '64',
		'cctld' => 'nz',
		'name_english' => 'New Zealand',
		'name_korean' => '뉴질랜드',
		'name_native' => 'New Zealand',
	),
	array(
		'iso_3166_1_alpha2' => 'NI',
		'iso_3166_1_alpha3' => 'NIC',
		'iso_3166_1_numeric' => '558',
		'calling_code' => '505',
		'cctld' => 'ni',
		'name_english' => 'Nicaragua',
		'name_korean' => '니카라과',
		'name_native' => 'Nicaragua',
	),
	array(
		'iso_3166_1_alpha2' => 'NE',
		'iso_3166_1_alpha3' => 'NER',
		'iso_3166_1_numeric' => '562',
		'calling_code' => '227',
		'cctld' => 'ne',
		'name_english' => 'Niger',
		'name_korean' => '니제르',
		'name_native' => 'Niger',
	),
	array(
		'iso_3166_1_alpha2' => 'NG',
		'iso_3166_1_alpha3' => 'NGA',
		'iso_3166_1_numeric' => '566',
		'calling_code' => '234',
		'cctld' => 'ng',
		'name_english' => 'Nigeria',
		'name_korean' => '나이지리아',
		'name_native' => 'Nigeria',
	),
	array(
		'iso_3166_1_alpha2' => 'NU',
		'iso_3166_1_alpha3' => 'NIU',
		'iso_3166_1_numeric' => '570',
		'calling_code' => '683',
		'cctld' => 'nu',
		'name_english' => 'Niue',
		'name_korean' => '니우에',
		'name_native' => 'Niuē',
	),
	array(
		'iso_3166_1_alpha2' => 'NF',
		'iso_3166_1_alpha3' => 'NFK',
		'iso_3166_1_numeric' => '574',
		'calling_code' => '672',
		'cctld' => 'nf',
		'name_english' => 'Norfolk Island',
		'name_korean' => '노퍽 섬',
		'name_native' => 'Norfolk Island',
	),
	array(
		'iso_3166_1_alpha2' => 'NO',
		'iso_3166_1_alpha3' => 'NOR',
		'iso_3166_1_numeric' => '578',
		'calling_code' => '47',
		'cctld' => 'no',
		'name_english' => 'Norway',
		'name_korean' => '노르웨이',
		'name_native' => 'Norge',
	),
	array(
		'iso_3166_1_alpha2' => 'MP',
		'iso_3166_1_alpha3' => 'MNP',
		'iso_3166_1_numeric' => '580',
		'calling_code' => '1-670',
		'cctld' => 'mp',
		'name_english' => 'Northern Mariana Islands',
		'name_korean' => '북마리아나 제도',
		'name_native' => 'Northern Mariana Islands',
	),
	array(
		'iso_3166_1_alpha2' => 'UM',
		'iso_3166_1_alpha3' => 'UMI',
		'iso_3166_1_numeric' => '581',
		'calling_code' => '',
		'cctld' => 'um',
		'name_english' => 'United States Minor Outlying Islands',
		'name_korean' => '미국령 군소 제도',
		'name_native' => 'United States Minor Outlying Islands',
	),
	array(
		'iso_3166_1_alpha2' => 'FM',
		'iso_3166_1_alpha3' => 'FSM',
		'iso_3166_1_numeric' => '583',
		'calling_code' => '691',
		'cctld' => 'fm',
		'name_english' => 'Federated States of Micronesia',
		'name_korean' => '미크로네시아 연방',
		'name_native' => 'Federated States of Micronesia',
	),
	array(
		'iso_3166_1_alpha2' => 'MH',
		'iso_3166_1_alpha3' => 'MHL',
		'iso_3166_1_numeric' => '584',
		'calling_code' => '692',
		'cctld' => 'mh',
		'name_english' => 'Marshall Islands',
		'name_korean' => '마셜 제도',
		'name_native' => 'Marshall Islands',
	),
	array(
		'iso_3166_1_alpha2' => 'PW',
		'iso_3166_1_alpha3' => 'PLW',
		'iso_3166_1_numeric' => '585',
		'calling_code' => '680',
		'cctld' => 'pw',
		'name_english' => 'Palau',
		'name_korean' => '팔라우',
		'name_native' => 'Belau',
	),
	array(
		'iso_3166_1_alpha2' => 'PK',
		'iso_3166_1_alpha3' => 'PAK',
		'iso_3166_1_numeric' => '586',
		'calling_code' => '92',
		'cctld' => 'pk',
		'name_english' => 'Pakistan',
		'name_korean' => '파키스탄',
		'name_native' => 'پاکستان',
	),
	array(
		'iso_3166_1_alpha2' => 'PA',
		'iso_3166_1_alpha3' => 'PAN',
		'iso_3166_1_numeric' => '591',
		'calling_code' => '507',
		'cctld' => 'pa',
		'name_english' => 'Panama',
		'name_korean' => '파나마',
		'name_native' => 'Panamá',
	),
	array(
		'iso_3166_1_alpha2' => 'PG',
		'iso_3166_1_alpha3' => 'PNG',
		'iso_3166_1_numeric' => '598',
		'calling_code' => '675',
		'cctld' => 'pg',
		'name_english' => 'Papua New Guinea',
		'name_korean' => '파푸아 뉴기니',
		'name_native' => 'Papua New Guinea',
	),
	array(
		'iso_3166_1_alpha2' => 'PY',
		'iso_3166_1_alpha3' => 'PRY',
		'iso_3166_1_numeric' => '600',
		'calling_code' => '595',
		'cctld' => 'py',
		'name_english' => 'Paraguay',
		'name_korean' => '파라과이',
		'name_native' => 'Paraguay',
	),
	array(
		'iso_3166_1_alpha2' => 'PE',
		'iso_3166_1_alpha3' => 'PER',
		'iso_3166_1_numeric' => '604',
		'calling_code' => '51',
		'cctld' => 'pe',
		'name_english' => 'Peru',
		'name_korean' => '페루',
		'name_native' => 'Perú',
	),
	array(
		'iso_3166_1_alpha2' => 'PH',
		'iso_3166_1_alpha3' => 'PHL',
		'iso_3166_1_numeric' => '608',
		'calling_code' => '63',
		'cctld' => 'ph',
		'name_english' => 'Philippines',
		'name_korean' => '필리핀',
		'name_native' => 'Pilipinas',
	),
	array(
		'iso_3166_1_alpha2' => 'PN',
		'iso_3166_1_alpha3' => 'PCN',
		'iso_3166_1_numeric' => '612',
		'calling_code' => '64',
		'cctld' => 'pn',
		'name_english' => 'Pitcairn Islands',
		'name_korean' => '핏케언 제도',
		'name_native' => 'Pitcairn Islands',
	),
	array(
		'iso_3166_1_alpha2' => 'PL',
		'iso_3166_1_alpha3' => 'POL',
		'iso_3166_1_numeric' => '616',
		'calling_code' => '48',
		'cctld' => 'pl',
		'name_english' => 'Poland',
		'name_korean' => '폴란드',
		'name_native' => 'Polska',
	),
	array(
		'iso_3166_1_alpha2' => 'PT',
		'iso_3166_1_alpha3' => 'PRT',
		'iso_3166_1_numeric' => '620',
		'calling_code' => '351',
		'cctld' => 'pt',
		'name_english' => 'Portugal',
		'name_korean' => '포르투갈',
		'name_native' => 'Portugal',
	),
	array(
		'iso_3166_1_alpha2' => 'GW',
		'iso_3166_1_alpha3' => 'GNB',
		'iso_3166_1_numeric' => '624',
		'calling_code' => '245',
		'cctld' => 'gw',
		'name_english' => 'Guinea-Bissau',
		'name_korean' => '기니비사우',
		'name_native' => 'Guiné-Bissau',
	),
	array(
		'iso_3166_1_alpha2' => 'TL',
		'iso_3166_1_alpha3' => 'TLS',
		'iso_3166_1_numeric' => '626',
		'calling_code' => '670',
		'cctld' => 'tl',
		'name_english' => 'East Timor',
		'name_korean' => '동티모르',
		'name_native' => 'Timor Lorosa\'e',
	),
	array(
		'iso_3166_1_alpha2' => 'PR',
		'iso_3166_1_alpha3' => 'PRI',
		'iso_3166_1_numeric' => '630',
		'calling_code' => '1',
		'cctld' => 'pr',
		'name_english' => 'Puerto Rico',
		'name_korean' => '푸에르토리코',
		'name_native' => 'Puerto Rico',
	),
	array(
		'iso_3166_1_alpha2' => 'QA',
		'iso_3166_1_alpha3' => 'QAT',
		'iso_3166_1_numeric' => '634',
		'calling_code' => '974',
		'cctld' => 'qa',
		'name_english' => 'Qatar',
		'name_korean' => '카타르',
		'name_native' => 'قطر',
	),
	array(
		'iso_3166_1_alpha2' => 'RE',
		'iso_3166_1_alpha3' => 'REU',
		'iso_3166_1_numeric' => '638',
		'calling_code' => '262',
		'cctld' => 're',
		'name_english' => 'Réunion',
		'name_korean' => '레위니옹',
		'name_native' => 'Réunion',
	),
	array(
		'iso_3166_1_alpha2' => 'RO',
		'iso_3166_1_alpha3' => 'ROU',
		'iso_3166_1_numeric' => '642',
		'calling_code' => '40',
		'cctld' => 'ro',
		'name_english' => 'Romania',
		'name_korean' => '루마니아',
		'name_native' => 'România',
	),
	array(
		'iso_3166_1_alpha2' => 'RU',
		'iso_3166_1_alpha3' => 'RUS',
		'iso_3166_1_numeric' => '643',
		'calling_code' => '7',
		'cctld' => 'ru',
		'name_english' => 'Russia',
		'name_korean' => '러시아',
		'name_native' => 'Россия',
	),
	array(
		'iso_3166_1_alpha2' => 'RW',
		'iso_3166_1_alpha3' => 'RWA',
		'iso_3166_1_numeric' => '646',
		'calling_code' => '250',
		'cctld' => 'rw',
		'name_english' => 'Rwanda',
		'name_korean' => '르완다',
		'name_native' => 'Rwanda',
	),
	array(
		'iso_3166_1_alpha2' => 'BL',
		'iso_3166_1_alpha3' => 'BLM',
		'iso_3166_1_numeric' => '652',
		'calling_code' => '590',
		'cctld' => 'bl',
		'name_english' => 'Saint Barthelemy',
		'name_korean' => '생바르텔레미',
		'name_native' => 'Saint-Barthélemy',
	),
	array(
		'iso_3166_1_alpha2' => 'SH',
		'iso_3166_1_alpha3' => 'SHN',
		'iso_3166_1_numeric' => '654',
		'calling_code' => '290',
		'cctld' => 'sh',
		'name_english' => 'Saint Helena',
		'name_korean' => '세인트헬레나',
		'name_native' => 'Saint Helena, Ascension and Tristan da Cunha',
	),
	array(
		'iso_3166_1_alpha2' => 'KN',
		'iso_3166_1_alpha3' => 'KNA',
		'iso_3166_1_numeric' => '659',
		'calling_code' => '1-869',
		'cctld' => 'kn',
		'name_english' => 'Saint Kitts and Nevis',
		'name_korean' => '세인트키츠 네비스',
		'name_native' => 'Saint Kitts and Nevis',
	),
	array(
		'iso_3166_1_alpha2' => 'AI',
		'iso_3166_1_alpha3' => 'AIA',
		'iso_3166_1_numeric' => '660',
		'calling_code' => '1-264',
		'cctld' => 'ai',
		'name_english' => 'Anguilla',
		'name_korean' => '앵귈라',
		'name_native' => 'Anguilla',
	),
	array(
		'iso_3166_1_alpha2' => 'LC',
		'iso_3166_1_alpha3' => 'LCA',
		'iso_3166_1_numeric' => '662',
		'calling_code' => '1-758',
		'cctld' => 'lc',
		'name_english' => 'Saint Lucia',
		'name_korean' => '세인트루시아',
		'name_native' => 'Saint Lucia',
	),
	array(
		'iso_3166_1_alpha2' => 'MF',
		'iso_3166_1_alpha3' => 'MAF',
		'iso_3166_1_numeric' => '663',
		'calling_code' => '590',
		'cctld' => 'mf',
		'name_english' => 'Saint Martin (French)',
		'name_korean' => '생마르탱 (프랑스령)',
		'name_native' => 'Saint-Martin',
	),
	array(
		'iso_3166_1_alpha2' => 'PM',
		'iso_3166_1_alpha3' => 'SPM',
		'iso_3166_1_numeric' => '666',
		'calling_code' => '508',
		'cctld' => 'pm',
		'name_english' => 'Saint Pierre and Miquelon',
		'name_korean' => '생피에르 미클롱',
		'name_native' => 'Saint-Pierre et Miquelon',
	),
	array(
		'iso_3166_1_alpha2' => 'VC',
		'iso_3166_1_alpha3' => 'VCT',
		'iso_3166_1_numeric' => '670',
		'calling_code' => '1-784',
		'cctld' => 'vc',
		'name_english' => 'Saint Vincent and the Grenadines',
		'name_korean' => '세인트빈센트 그레나',
		'name_native' => 'Saint Vincent and the Grenadines',
	),
	array(
		'iso_3166_1_alpha2' => 'SM',
		'iso_3166_1_alpha3' => 'SMR',
		'iso_3166_1_numeric' => '674',
		'calling_code' => '378',
		'cctld' => 'sm',
		'name_english' => 'San Marino',
		'name_korean' => '산마리노',
		'name_native' => 'San Marino',
	),
	array(
		'iso_3166_1_alpha2' => 'ST',
		'iso_3166_1_alpha3' => 'STP',
		'iso_3166_1_numeric' => '678',
		'calling_code' => '239',
		'cctld' => 'st',
		'name_english' => 'Sao Tome and Principe',
		'name_korean' => '상투메 프린시페',
		'name_native' => 'São Tomé e Príncipe',
	),
	array(
		'iso_3166_1_alpha2' => 'SA',
		'iso_3166_1_alpha3' => 'SAU',
		'iso_3166_1_numeric' => '682',
		'calling_code' => '966',
		'cctld' => 'sa',
		'name_english' => 'Saudi Arabia',
		'name_korean' => '사우디아라비아',
		'name_native' => 'المملكة العربية السعودية',
	),
	array(
		'iso_3166_1_alpha2' => 'SN',
		'iso_3166_1_alpha3' => 'SEN',
		'iso_3166_1_numeric' => '686',
		'calling_code' => '221',
		'cctld' => 'sn',
		'name_english' => 'Senegal',
		'name_korean' => '세네갈',
		'name_native' => 'Sénégal',
	),
	array(
		'iso_3166_1_alpha2' => 'RS',
		'iso_3166_1_alpha3' => 'SRB',
		'iso_3166_1_numeric' => '688',
		'calling_code' => '381',
		'cctld' => 'rs',
		'name_english' => 'Serbia',
		'name_korean' => '세르비아',
		'name_native' => 'Србија',
	),
	array(
		'iso_3166_1_alpha2' => 'SC',
		'iso_3166_1_alpha3' => 'SYC',
		'iso_3166_1_numeric' => '690',
		'calling_code' => '248',
		'cctld' => 'sc',
		'name_english' => 'Seychelles',
		'name_korean' => '세이셸',
		'name_native' => 'Sesel',
	),
	array(
		'iso_3166_1_alpha2' => 'SL',
		'iso_3166_1_alpha3' => 'SLE',
		'iso_3166_1_numeric' => '694',
		'calling_code' => '232',
		'cctld' => 'sl',
		'name_english' => 'Sierra Leone',
		'name_korean' => '시에라리온',
		'name_native' => 'Sierra Leone',
	),
	array(
		'iso_3166_1_alpha2' => 'SG',
		'iso_3166_1_alpha3' => 'SGP',
		'iso_3166_1_numeric' => '702',
		'calling_code' => '65',
		'cctld' => 'sg',
		'name_english' => 'Singapore',
		'name_korean' => '싱가포르',
		'name_native' => 'Singapura',
	),
	array(
		'iso_3166_1_alpha2' => 'SK',
		'iso_3166_1_alpha3' => 'SVK',
		'iso_3166_1_numeric' => '703',
		'calling_code' => '421',
		'cctld' => 'sk',
		'name_english' => 'Slovakia',
		'name_korean' => '슬로바키아',
		'name_native' => 'Slovensko',
	),
	array(
		'iso_3166_1_alpha2' => 'VN',
		'iso_3166_1_alpha3' => 'VNM',
		'iso_3166_1_numeric' => '704',
		'calling_code' => '84',
		'cctld' => 'vn',
		'name_english' => 'Vietnam',
		'name_korean' => '베트남',
		'name_native' => 'Việt Nam',
	),
	array(
		'iso_3166_1_alpha2' => 'SI',
		'iso_3166_1_alpha3' => 'SVN',
		'iso_3166_1_numeric' => '705',
		'calling_code' => '386',
		'cctld' => 'si',
		'name_english' => 'Slovenia',
		'name_korean' => '슬로베니아',
		'name_native' => 'Slovenija',
	),
	array(
		'iso_3166_1_alpha2' => 'SO',
		'iso_3166_1_alpha3' => 'SOM',
		'iso_3166_1_numeric' => '706',
		'calling_code' => '252',
		'cctld' => 'so',
		'name_english' => 'Somalia',
		'name_korean' => '소말리아',
		'name_native' => 'الصومال',
	),
	array(
		'iso_3166_1_alpha2' => 'ZA',
		'iso_3166_1_alpha3' => 'ZAF',
		'iso_3166_1_numeric' => '710',
		'calling_code' => '27',
		'cctld' => 'za',
		'name_english' => 'South Africa',
		'name_korean' => '남아프리카 공화국',
		'name_native' => 'South Africa',
	),
	array(
		'iso_3166_1_alpha2' => 'ZW',
		'iso_3166_1_alpha3' => 'ZWE',
		'iso_3166_1_numeric' => '716',
		'calling_code' => '263',
		'cctld' => 'zw',
		'name_english' => 'Zimbabwe',
		'name_korean' => '짐바브웨',
		'name_native' => 'Zimbabwe',
	),
	array(
		'iso_3166_1_alpha2' => 'ES',
		'iso_3166_1_alpha3' => 'ESP',
		'iso_3166_1_numeric' => '724',
		'calling_code' => '34',
		'cctld' => 'es',
		'name_english' => 'Spain',
		'name_korean' => '스페인',
		'name_native' => 'España',
	),
	array(
		'iso_3166_1_alpha2' => 'SS',
		'iso_3166_1_alpha3' => 'SSD',
		'iso_3166_1_numeric' => '728',
		'calling_code' => '211',
		'cctld' => 'ss',
		'name_english' => 'South Sudan',
		'name_korean' => '남수단',
		'name_native' => 'South Sudan',
	),
	array(
		'iso_3166_1_alpha2' => 'SD',
		'iso_3166_1_alpha3' => 'SDN',
		'iso_3166_1_numeric' => '729',
		'calling_code' => '249',
		'cctld' => 'sd',
		'name_english' => 'Sudan',
		'name_korean' => '수단',
		'name_native' => 'السودان',
	),
	array(
		'iso_3166_1_alpha2' => 'EH',
		'iso_3166_1_alpha3' => 'ESH',
		'iso_3166_1_numeric' => '732',
		'calling_code' => '212',
		'cctld' => 'eh',
		'name_english' => 'Western Sahara',
		'name_korean' => '서사하라',
		'name_native' => 'الصحراء الغربية',
	),
	array(
		'iso_3166_1_alpha2' => 'SR',
		'iso_3166_1_alpha3' => 'SUR',
		'iso_3166_1_numeric' => '740',
		'calling_code' => '597',
		'cctld' => 'sr',
		'name_english' => 'Suriname',
		'name_korean' => '수리남',
		'name_native' => 'Suriname',
	),
	array(
		'iso_3166_1_alpha2' => 'SJ',
		'iso_3166_1_alpha3' => 'SJM',
		'iso_3166_1_numeric' => '744',
		'calling_code' => '47',
		'cctld' => 'sj',
		'name_english' => 'Svalbard',
		'name_korean' => '스발바르',
		'name_native' => 'Svalbard',
	),
	array(
		'iso_3166_1_alpha2' => 'SZ',
		'iso_3166_1_alpha3' => 'SWZ',
		'iso_3166_1_numeric' => '748',
		'calling_code' => '268',
		'cctld' => 'sz',
		'name_english' => 'Swaziland',
		'name_korean' => '스와질란드',
		'name_native' => 'Umbuso weSwatini',
	),
	array(
		'iso_3166_1_alpha2' => 'SE',
		'iso_3166_1_alpha3' => 'SWE',
		'iso_3166_1_numeric' => '752',
		'calling_code' => '46',
		'cctld' => 'se',
		'name_english' => 'Sweden',
		'name_korean' => '스웨덴',
		'name_native' => 'Sverige',
	),
	array(
		'iso_3166_1_alpha2' => 'CH',
		'iso_3166_1_alpha3' => 'CHE',
		'iso_3166_1_numeric' => '756',
		'calling_code' => '41',
		'cctld' => 'ch',
		'name_english' => 'Switzerland',
		'name_korean' => '스위스',
		'name_native' => 'Schweiz, Suisse, Svizzera, Svizra',
	),
	array(
		'iso_3166_1_alpha2' => 'SY',
		'iso_3166_1_alpha3' => 'SYR',
		'iso_3166_1_numeric' => '760',
		'calling_code' => '963',
		'cctld' => 'sy',
		'name_english' => 'Syria',
		'name_korean' => '시리아',
		'name_native' => 'سورية',
	),
	array(
		'iso_3166_1_alpha2' => 'TJ',
		'iso_3166_1_alpha3' => 'TJK',
		'iso_3166_1_numeric' => '762',
		'calling_code' => '992',
		'cctld' => 'tj',
		'name_english' => 'Tajikistan',
		'name_korean' => '타지키스탄',
		'name_native' => 'Тоҷикистон',
	),
	array(
		'iso_3166_1_alpha2' => 'TH',
		'iso_3166_1_alpha3' => 'THA',
		'iso_3166_1_numeric' => '764',
		'calling_code' => '66',
		'cctld' => 'th',
		'name_english' => 'Thailand',
		'name_korean' => '태국',
		'name_native' => 'ประเทศไทย',
	),
	array(
		'iso_3166_1_alpha2' => 'TG',
		'iso_3166_1_alpha3' => 'TGO',
		'iso_3166_1_numeric' => '768',
		'calling_code' => '228',
		'cctld' => 'tg',
		'name_english' => 'Togo',
		'name_korean' => '토고',
		'name_native' => 'Togo',
	),
	array(
		'iso_3166_1_alpha2' => 'TK',
		'iso_3166_1_alpha3' => 'TKL',
		'iso_3166_1_numeric' => '772',
		'calling_code' => '690',
		'cctld' => 'tk',
		'name_english' => 'Tokelau',
		'name_korean' => '토켈라우',
		'name_native' => 'Tokelau',
	),
	array(
		'iso_3166_1_alpha2' => 'TO',
		'iso_3166_1_alpha3' => 'TON',
		'iso_3166_1_numeric' => '776',
		'calling_code' => '676',
		'cctld' => 'to',
		'name_english' => 'Tonga',
		'name_korean' => '통가',
		'name_native' => 'Tonga',
	),
	array(
		'iso_3166_1_alpha2' => 'TT',
		'iso_3166_1_alpha3' => 'TTO',
		'iso_3166_1_numeric' => '780',
		'calling_code' => '1-868',
		'cctld' => 'tt',
		'name_english' => 'Trinidad and Tobago',
		'name_korean' => '트리니다드 토바고',
		'name_native' => 'Trinidad and Tobago',
	),
	array(
		'iso_3166_1_alpha2' => 'AE',
		'iso_3166_1_alpha3' => 'ARE',
		'iso_3166_1_numeric' => '784',
		'calling_code' => '971',
		'cctld' => 'ae',
		'name_english' => 'United Arab Emirates',
		'name_korean' => '아랍에미리트',
		'name_native' => 'الإمارات العربيّة المتّحدة',
	),
	array(
		'iso_3166_1_alpha2' => 'TN',
		'iso_3166_1_alpha3' => 'TUN',
		'iso_3166_1_numeric' => '788',
		'calling_code' => '216',
		'cctld' => 'tn',
		'name_english' => 'Tunisia',
		'name_korean' => '튀니지',
		'name_native' => 'تونس',
	),
	array(
		'iso_3166_1_alpha2' => 'TR',
		'iso_3166_1_alpha3' => 'TUR',
		'iso_3166_1_numeric' => '792',
		'calling_code' => '90',
		'cctld' => 'tr',
		'name_english' => 'Turkey',
		'name_korean' => '터키',
		'name_native' => 'Türkiye',
	),
	array(
		'iso_3166_1_alpha2' => 'TM',
		'iso_3166_1_alpha3' => 'TKM',
		'iso_3166_1_numeric' => '795',
		'calling_code' => '993',
		'cctld' => 'tm',
		'name_english' => 'Turkmenistan',
		'name_korean' => '투르크메니스탄',
		'name_native' => 'Türkmenistan',
	),
	array(
		'iso_3166_1_alpha2' => 'TC',
		'iso_3166_1_alpha3' => 'TCA',
		'iso_3166_1_numeric' => '796',
		'calling_code' => '1-649',
		'cctld' => 'tc',
		'name_english' => 'Turks and Caicos Islands',
		'name_korean' => '터크스 케이커스 제도',
		'name_native' => 'Turks and Caicos Islands',
	),
	array(
		'iso_3166_1_alpha2' => 'TV',
		'iso_3166_1_alpha3' => 'TUV',
		'iso_3166_1_numeric' => '798',
		'calling_code' => '688',
		'cctld' => 'tv',
		'name_english' => 'Tuvalu',
		'name_korean' => '투발루',
		'name_native' => 'Tuvalu',
	),
	array(
		'iso_3166_1_alpha2' => 'UG',
		'iso_3166_1_alpha3' => 'UGA',
		'iso_3166_1_numeric' => '800',
		'calling_code' => '256',
		'cctld' => 'ug',
		'name_english' => 'Uganda',
		'name_korean' => '우간다',
		'name_native' => 'Uganda',
	),
	array(
		'iso_3166_1_alpha2' => 'UA',
		'iso_3166_1_alpha3' => 'UKR',
		'iso_3166_1_numeric' => '804',
		'calling_code' => '380',
		'cctld' => 'ua',
		'name_english' => 'Ukraine',
		'name_korean' => '우크라이나',
		'name_native' => 'Україна',
	),
	array(
		'iso_3166_1_alpha2' => 'MK',
		'iso_3166_1_alpha3' => 'MKD',
		'iso_3166_1_numeric' => '807',
		'calling_code' => '389',
		'cctld' => 'mk',
		'name_english' => 'Macedonia',
		'name_korean' => '마케도니아',
		'name_native' => 'Македонија',
	),
	array(
		'iso_3166_1_alpha2' => 'EG',
		'iso_3166_1_alpha3' => 'EGY',
		'iso_3166_1_numeric' => '818',
		'calling_code' => '20',
		'cctld' => 'eg',
		'name_english' => 'Egypt',
		'name_korean' => '이집트',
		'name_native' => 'مصر',
	),
	array(
		'iso_3166_1_alpha2' => 'GB',
		'iso_3166_1_alpha3' => 'GBR',
		'iso_3166_1_numeric' => '826',
		'calling_code' => '44',
		'cctld' => 'gb',
		'name_english' => 'United Kingdom',
		'name_korean' => '영국',
		'name_native' => 'United Kingdom',
	),
	array(
		'iso_3166_1_alpha2' => 'GG',
		'iso_3166_1_alpha3' => 'GGY',
		'iso_3166_1_numeric' => '831',
		'calling_code' => '44-1481',
		'cctld' => 'gg',
		'name_english' => 'Guernsey',
		'name_korean' => '건지 섬',
		'name_native' => 'Guernsey',
	),
	array(
		'iso_3166_1_alpha2' => 'JE',
		'iso_3166_1_alpha3' => 'JEY',
		'iso_3166_1_numeric' => '832',
		'calling_code' => '44-1534',
		'cctld' => 'je',
		'name_english' => 'Jersey',
		'name_korean' => '저지 섬',
		'name_native' => 'Jersey',
	),
	array(
		'iso_3166_1_alpha2' => 'IM',
		'iso_3166_1_alpha3' => 'IMN',
		'iso_3166_1_numeric' => '833',
		'calling_code' => '44-1624',
		'cctld' => 'im',
		'name_english' => 'Isle of Man',
		'name_korean' => '맨 섬',
		'name_native' => 'Isle of Man',
	),
	array(
		'iso_3166_1_alpha2' => 'TZ',
		'iso_3166_1_alpha3' => 'TZA',
		'iso_3166_1_numeric' => '834',
		'calling_code' => '255',
		'cctld' => 'tz',
		'name_english' => 'Tanzania',
		'name_korean' => '탄자니아',
		'name_native' => 'Tanzania',
	),
	array(
		'iso_3166_1_alpha2' => 'US',
		'iso_3166_1_alpha3' => 'USA',
		'iso_3166_1_numeric' => '840',
		'calling_code' => '1',
		'cctld' => 'us',
		'name_english' => 'United States of America',
		'name_korean' => '미국',
		'name_native' => 'United States of America',
	),
	array(
		'iso_3166_1_alpha2' => 'VI',
		'iso_3166_1_alpha3' => 'VIR',
		'iso_3166_1_numeric' => '850',
		'calling_code' => '1-340',
		'cctld' => 'vi',
		'name_english' => 'Virgin Islands (U.S.)',
		'name_korean' => '미국령 버진아일랜드',
		'name_native' => 'Virgin Islands (U.S.)',
	),
	array(
		'iso_3166_1_alpha2' => 'BF',
		'iso_3166_1_alpha3' => 'BFA',
		'iso_3166_1_numeric' => '854',
		'calling_code' => '226',
		'cctld' => 'bf',
		'name_english' => 'Burkina Faso',
		'name_korean' => '부르키나파소',
		'name_native' => 'Burkina Faso',
	),
	array(
		'iso_3166_1_alpha2' => 'UY',
		'iso_3166_1_alpha3' => 'URY',
		'iso_3166_1_numeric' => '858',
		'calling_code' => '598',
		'cctld' => 'uy',
		'name_english' => 'Uruguay',
		'name_korean' => '우루과이',
		'name_native' => 'Uruguay',
	),
	array(
		'iso_3166_1_alpha2' => 'UZ',
		'iso_3166_1_alpha3' => 'UZB',
		'iso_3166_1_numeric' => '860',
		'calling_code' => '998',
		'cctld' => 'uz',
		'name_english' => 'Uzbekistan',
		'name_korean' => '우즈베키스탄',
		'name_native' => 'Ўзбекистон',
	),
	array(
		'iso_3166_1_alpha2' => 'VE',
		'iso_3166_1_alpha3' => 'VEN',
		'iso_3166_1_numeric' => '862',
		'calling_code' => '58',
		'cctld' => 've',
		'name_english' => 'Venezuela',
		'name_korean' => '베네수엘라',
		'name_native' => 'Venezuela',
	),
	array(
		'iso_3166_1_alpha2' => 'WF',
		'iso_3166_1_alpha3' => 'WLF',
		'iso_3166_1_numeric' => '876',
		'calling_code' => '681',
		'cctld' => 'wf',
		'name_english' => 'Wallis and Futuna',
		'name_korean' => '왈리스 퓌튀나',
		'name_native' => 'Wallis-et-Futuna',
	),
	array(
		'iso_3166_1_alpha2' => 'WS',
		'iso_3166_1_alpha3' => 'WSM',
		'iso_3166_1_numeric' => '882',
		'calling_code' => '685',
		'cctld' => 'ws',
		'name_english' => 'Samoa',
		'name_korean' => '사모아',
		'name_native' => 'Samoa',
	),
	array(
		'iso_3166_1_alpha2' => 'YE',
		'iso_3166_1_alpha3' => 'YEM',
		'iso_3166_1_numeric' => '887',
		'calling_code' => '967',
		'cctld' => 'ye',
		'name_english' => 'Yemen',
		'name_korean' => '예멘',
		'name_native' => 'اليمن',
	),
	array(
		'iso_3166_1_alpha2' => 'ZM',
		'iso_3166_1_alpha3' => 'ZMB',
		'iso_3166_1_numeric' => '894',
		'calling_code' => '260',
		'cctld' => 'zm',
		'name_english' => 'Zambia',
		'name_korean' => '잠비아',
		'name_native' => 'Zambia',
	),
);
